name: Build image and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-demo-image:${{ github.sha }}
    
    - name: Scan the Docker image wiht Aqua
      run: docker run -e registry.aquasec.com/scanner:2402.8.22 --token fd1cf36d86f5ab2a39e49b9bb157694f8fdca47e --host https://08c048c27d-d.cloud.aquasec.com --no-verify --verbose-errors --local my-demo-image:${{ github.sha }}

    - name: Tag image with Registry
      run: docker tag my-demo-image:${{ github.sha }} my-registry/my-demo-image:${{ github.sha }}

    - name: Push to Registry
      run: echo "docker push my-registry/my-demo-image:${{ github.sha }}"
